import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import reportWebVitals from './reportWebVitals';
import LocationCard from './components/LocationCard';

let report={"hourly": [
  {
      "time": "2024-03-07T10:00:00Z",
      "values": {
          "cloudBase": 0.78,
          "cloudCeiling": 0.78,
          "cloudCover": 52,
          "dewPoint": 3.38,
          "evapotranspiration": 0.185,
          "freezingRainIntensity": 0,
          "humidity": 65,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 0,
          "pressureSurfaceLevel": 942.61,
          "rainAccumulation": 0,
          "rainAccumulationLwe": 0,
          "rainIntensity": 0,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 9.69,
          "temperatureApparent": 9.69,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 16,
          "weatherCode": 1101,
          "windDirection": 186.69,
          "windGust": 4.63,
          "windSpeed": 1
      }
  },
  {
      "time": "2024-03-07T11:00:00Z",
      "values": {
          "cloudBase": 0.77,
          "cloudCeiling": null,
          "cloudCover": 57.03,
          "dewPoint": 2.23,
          "evapotranspiration": 0.25,
          "freezingRainIntensity": 0,
          "humidity": 63.2,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 0,
          "pressureSurfaceLevel": 942.33,
          "rainAccumulation": 0,
          "rainAccumulationLwe": 0,
          "rainIntensity": 0,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 8.83,
          "temperatureApparent": 8.83,
          "uvHealthConcern": 0,
          "uvIndex": 1,
          "visibility": 16,
          "weatherCode": 1101,
          "windDirection": 185.44,
          "windGust": 6.1,
          "windSpeed": 1.64
      }
  },
  {
      "time": "2024-03-07T12:00:00Z",
      "values": {
          "cloudBase": 0.56,
          "cloudCeiling": null,
          "cloudCover": 49.22,
          "dewPoint": 3.06,
          "evapotranspiration": 0.23,
          "freezingRainIntensity": 0,
          "humidity": 71.95,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 0,
          "pressureSurfaceLevel": 942.16,
          "rainAccumulation": 0,
          "rainAccumulationLwe": 0.1,
          "rainIntensity": 0,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 7.8,
          "temperatureApparent": 7.8,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 10.33,
          "weatherCode": 1101,
          "windDirection": 168.79,
          "windGust": 6.05,
          "windSpeed": 1.67
      }
  },
  {
      "time": "2024-03-07T13:00:00Z",
      "values": {
          "cloudBase": 0.46,
          "cloudCeiling": 0.7,
          "cloudCover": 100,
          "dewPoint": 3.16,
          "evapotranspiration": 0.172,
          "freezingRainIntensity": 0,
          "humidity": 76.55,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 8,
          "pressureSurfaceLevel": 942.05,
          "rainAccumulation": 0.1,
          "rainAccumulationLwe": 0.32,
          "rainIntensity": 0.27,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 7,
          "temperatureApparent": 7,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 6.08,
          "weatherCode": 4000,
          "windDirection": 170.91,
          "windGust": 6.02,
          "windSpeed": 1.62
      }
  },
  {
      "time": "2024-03-07T14:00:00Z",
      "values": {
          "cloudBase": 0.3,
          "cloudCeiling": 0.61,
          "cloudCover": 86.72,
          "dewPoint": 3.96,
          "evapotranspiration": 0.098,
          "freezingRainIntensity": 0,
          "humidity": 84.71,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 5,
          "pressureSurfaceLevel": 942.05,
          "rainAccumulation": 0.91,
          "rainAccumulationLwe": 0.1,
          "rainIntensity": 0.37,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 6.34,
          "temperatureApparent": 6.34,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 6.91,
          "weatherCode": 4000,
          "windDirection": 163.33,
          "windGust": 5.01,
          "windSpeed": 1.35
      }
  },
  {
      "time": "2024-03-07T15:00:00Z",
      "values": {
          "cloudBase": 0.38,
          "cloudCeiling": 0.55,
          "cloudCover": 94.53,
          "dewPoint": 3.7,
          "evapotranspiration": 0.049,
          "freezingRainIntensity": 0,
          "humidity": 82.61,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 5,
          "pressureSurfaceLevel": 941.63,
          "rainAccumulation": 0,
          "rainAccumulationLwe": 0.09,
          "rainIntensity": 0.1,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 6.44,
          "temperatureApparent": 6.44,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 9.79,
          "weatherCode": 1001,
          "windDirection": 124.42,
          "windGust": 4.37,
          "windSpeed": 1.26
      }
  },
  {
      "time": "2024-03-07T16:00:00Z",
      "values": {
          "cloudBase": 0.63,
          "cloudCeiling": 1.23,
          "cloudCover": 91.41,
          "dewPoint": 3.16,
          "evapotranspiration": 0.02,
          "freezingRainIntensity": 0,
          "humidity": 81.46,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 5,
          "pressureSurfaceLevel": 941.57,
          "rainAccumulation": 0,
          "rainAccumulationLwe": 1.56,
          "rainIntensity": 0.09,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 6.09,
          "temperatureApparent": 6.09,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 11.4,
          "weatherCode": 1001,
          "windDirection": 124.46,
          "windGust": 3.84,
          "windSpeed": 1.32
      }
  },
  {
      "time": "2024-03-07T17:00:00Z",
      "values": {
          "cloudBase": 0.76,
          "cloudCeiling": 1.21,
          "cloudCover": 85.94,
          "dewPoint": 3.39,
          "evapotranspiration": 0,
          "freezingRainIntensity": 0,
          "humidity": 88.83,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 5,
          "pressureSurfaceLevel": 941.6,
          "rainAccumulation": 0.34,
          "rainAccumulationLwe": 1.33,
          "rainIntensity": 1.56,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 5.08,
          "temperatureApparent": 5.08,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 12.28,
          "weatherCode": 4200,
          "windDirection": 119.26,
          "windGust": 2.55,
          "windSpeed": 0.76
      }
  },
  {
      "time": "2024-03-07T18:00:00Z",
      "values": {
          "cloudBase": 0.51,
          "cloudCeiling": 1.5,
          "cloudCover": 86.72,
          "dewPoint": 3.11,
          "evapotranspiration": 0.01,
          "freezingRainIntensity": 0,
          "humidity": 93.12,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 5,
          "pressureSurfaceLevel": 942.15,
          "rainAccumulation": 1.96,
          "rainAccumulationLwe": 0.56,
          "rainIntensity": 1.33,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 1.99,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 4.12,
          "temperatureApparent": 4.12,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 9.01,
          "weatherCode": 4200,
          "windDirection": 21.78,
          "windGust": 1.79,
          "windSpeed": 0.61
      }
  },
  {
      "time": "2024-03-07T19:00:00Z",
      "values": {
          "cloudBase": 0.76,
          "cloudCeiling": null,
          "cloudCover": 74.22,
          "dewPoint": 2.7,
          "evapotranspiration": 0.01,
          "freezingRainIntensity": 0,
          "humidity": 93.04,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 10,
          "pressureSurfaceLevel": 942.13,
          "rainAccumulation": 1.38,
          "rainAccumulationLwe": 0.42,
          "rainIntensity": 0.56,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0.87,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 3.72,
          "temperatureApparent": 3.72,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 6.2,
          "weatherCode": 4200,
          "windDirection": 59.02,
          "windGust": 2.6,
          "windSpeed": 0.74
      }
  },
  {
      "time": "2024-03-07T20:00:00Z",
      "values": {
          "cloudBase": 0.66,
          "cloudCeiling": 1.18,
          "cloudCover": 92.97,
          "dewPoint": 2.21,
          "evapotranspiration": 0.009,
          "freezingRainIntensity": 0,
          "humidity": 95.59,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 10,
          "pressureSurfaceLevel": 942.4,
          "rainAccumulation": 0.9,
          "rainAccumulationLwe": 0.45,
          "rainIntensity": 0.42,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0.51,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 2.85,
          "temperatureApparent": 1.69,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 7.61,
          "weatherCode": 4000,
          "windDirection": 47.27,
          "windGust": 3.7,
          "windSpeed": 1.36
      }
  },
  {
      "time": "2024-03-07T21:00:00Z",
      "values": {
          "cloudBase": 0.59,
          "cloudCeiling": 0.73,
          "cloudCover": 100,
          "dewPoint": 2.67,
          "evapotranspiration": 0.009,
          "freezingRainIntensity": 0,
          "humidity": 95.52,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 10,
          "pressureSurfaceLevel": 942.79,
          "rainAccumulation": 0.46,
          "rainAccumulationLwe": 0.08,
          "rainIntensity": 0.45,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 3.32,
          "temperatureApparent": 3.32,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 5.67,
          "weatherCode": 4000,
          "windDirection": 60.88,
          "windGust": 2.76,
          "windSpeed": 0.86
      }
  },
  {
      "time": "2024-03-07T22:00:00Z",
      "values": {
          "cloudBase": 0.61,
          "cloudCeiling": 0.84,
          "cloudCover": 100,
          "dewPoint": 2.64,
          "evapotranspiration": 0.01,
          "freezingRainIntensity": 0,
          "humidity": 92.54,
          "iceAccumulation": 0,
          "iceAccumulationLwe": 0,
          "precipitationProbability": 10,
          "pressureSurfaceLevel": 942.86,
          "rainAccumulation": 0.3,
          "rainAccumulationLwe": 0.08,
          "rainIntensity": 0.08,
          "sleetAccumulation": 0,
          "sleetAccumulationLwe": 0,
          "sleetIntensity": 0,
          "snowAccumulation": 0,
          "snowAccumulationLwe": 0,
          "snowIntensity": 0,
          "temperature": 3.74,
          "temperatureApparent": 3.74,
          "uvHealthConcern": 0,
          "uvIndex": 0,
          "visibility": 8.77,
          "weatherCode": 1001,
          "windDirection": 79.32,
          "windGust": 1.89,
          "windSpeed": 0.49
      }
  }        
]}


const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <LocationCard reportAPI={report.hourly}/>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
